/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Registro extends javax.swing.JFrame {

     conexionSQL  cc=new conexionSQL();
     Connection con=cc.conexion();
  
     
     
     
   
    
  
    public Registro() {
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
          mostarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
     public void ActualizarDatos(){
    
    try{
        String SQL="update  Registro set Nombre_completo=?,Nacionalidad=?,Tipo_documento=?,Numero_documento=?,Telefono=?,Localidad=?,Direccion=?,Correo_electronico=?,contraseña=? where id=?";
       
        int filaSelecionado=TablaRegistro.getSelectedRow();
        String dao=(String)TablaRegistro.getValueAt(filaSelecionado,0);
        
        PreparedStatement pst=con.prepareStatement (SQL);
        
        
        pst.setString(1, txtnombrecompleto.getText());
        pst.setString(2, txtnacionalidad.getText());
        
        int seleccionado=cbTipodocumento.getSelectedIndex();
        pst.setString(3, cbTipodocumento.getItemAt(seleccionado));
        pst.setString(4, txtNumero_Documento.getText());
        
        pst.setString(5, txtTelefono.getText());
         int selec=cbLocalidad.getSelectedIndex();
        pst.setString(6, cbLocalidad.getItemAt(selec));
            
        pst.setString(7, txtDireccion.getText());
        pst.setString(8, txtCorreo_Electronico.getText());
      
        pst.setString(9, txtContraseña.getText());
      
     
        
      
         pst.setString(10,dao);
         pst.execute();
         
         
         JOptionPane.showMessageDialog(null,"Actualizacion Exitoso");
         
         
    } catch(Exception e){
         JOptionPane.showMessageDialog(null,"Error en ACTUALIZACION" +e.getMessage());
    
    }
    
    }
    
   public  void mostarDatos(){
   
   String[] titulos= {"id","Nombre completo ","Nacionalidad","Tipo de documento","Numero de documento","Telefono","Localidad","Direccion","Correo electronico","Contraseña"};
   String[] registros=new String[10];
   
   DefaultTableModel model=new DefaultTableModel(null,titulos);
   
   String SQL="select*from registro";
   try{
       
       
       Statement st=con.createStatement();
       ResultSet rs=st.executeQuery(SQL);
       
       
       while(rs.next()){
       registros[0]=rs.getString("id");   
       registros[1]=rs.getString("Nombre_completo");
       registros[2]=rs.getString("Nacionalidad");
       registros[3]=rs.getString("Tipo_documento");
       registros[4]=rs.getString("Numero_documento");
       registros[5]=rs.getString("Telefono");
       registros[6]=rs.getString("Localidad");
       registros[7]=rs.getString("Direccion");
       registros[8]=rs.getString("Correo_electronico");
       registros[9]=rs.getString("Contraseña");
       
       model.addRow(registros);
       }
               
     TablaRegistro.setModel(model);
     
   } catch (Exception e){
   
   JOptionPane.showMessageDialog(null,"Error al mostrar datos"+ e.getMessage());
   }
   
   
   }
   public void eliminarRegistro(){
       
       int filaSeleccionada=TablaRegistro.getSelectedRow();
       
       try
       {
           String SQL="delete from registro where id="+TablaRegistro.getValueAt(filaSeleccionada,0);
           
           Statement st=con.createStatement();
           
           int n=st.executeUpdate(SQL);
           
           if(n>=0){
           
           
           JOptionPane.showMessageDialog(null,"Registro Eliminado");
           }
           
       }catch (Exception e){
           JOptionPane.showMessageDialog(null,"Registro Eliminado" + e.getMessage());
       }
   }
           
   public void limpiarCajas(){
   
   txtnombrecompleto.setText("");
   txtnacionalidad.setText("");
   cbTipodocumento.setSelectedItem(null);
   txtNumero_Documento.setText("");
   txtTelefono.setText("");
   cbLocalidad.setSelectedItem(null);
   txtDireccion.setText("");
   txtCorreo_Electronico.setText("");
   txtContraseña.setText("");
           
   } 
          
    public void insertarDatos(){
    
    try{
        String SQL="insert into Registro (Nombre_completo,Nacionalidad,Tipo_documento,Numero_documento,Telefono,Localidad,Direccion,Correo_electronico,contraseña) values(?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst=con.prepareCall(SQL);
        
        
        pst.setString(1, txtnombrecompleto.getText());
        pst.setString(2, txtnacionalidad.getText());
        
        int seleccionado=cbTipodocumento.getSelectedIndex();
        pst.setString(3, cbTipodocumento.getItemAt(seleccionado));
        pst.setString(4, txtNumero_Documento.getText());
        
        pst.setString(5, txtTelefono.getText());
         int selec=cbLocalidad.getSelectedIndex();
        pst.setString(6, cbLocalidad.getItemAt(selec));
            
        pst.setString(7, txtDireccion.getText());
        pst.setString(8, txtCorreo_Electronico.getText());
      
        pst.setString(9, txtContraseña.getText());
      
     
        
      
         
         pst.execute();
         
         
         JOptionPane.showMessageDialog(null,"Registro Exitoso");
         
         
    } catch(Exception e){
         JOptionPane.showMessageDialog(null,"Error en el Registro" +e.getMessage());
    
    }
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombrecompleto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnacionalidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        cbTipodocumento = new javax.swing.JComboBox<>();
        cbLocalidad = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtNumero_Documento = new javax.swing.JTextField();
        txtCorreo_Electronico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRegistro = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre completo ");

        txtnombrecompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecompletoActionPerformed(evt);
            }
        });

        jLabel2.setText("Localidad");

        jLabel4.setText("Nacionalidad");

        txtnacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnacionalidadActionPerformed(evt);
            }
        });

        jLabel3.setText("Direccion");

        jLabel5.setText("Tipo de documento ");

        jLabel6.setText("Numero de documento ");

        jLabel7.setText("Telefono");

        jLabel8.setText("Correo electronico ");

        jLabel9.setText("Contraseña");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        cbTipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de documento", "Cedula de ciudadania ", "Cedula Extrangera", "Trajeta de identidad ", "Otros" }));

        cbLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Localidad", "Antonio nariño ", "Barrios unidos", "Bosa ", "Chapinero", "Ciudad bolivar ", "Engativa", "Fontibon", "Kennedy", "La candelaria", "Los martires", "Puente aranda ", "Rafael  uribe uribe ", "San cristobal ", "Santa fe ", "Suba ", "Sumapaz", "Teusaquillo", "Tunjelito", "Usaquen", "Usme" }));
        cbLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocalidadActionPerformed(evt);
            }
        });

        txtNumero_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero_DocumentoActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setMaximumSize(new java.awt.Dimension(410, 148));
        jLabel11.setMinimumSize(new java.awt.Dimension(430, 148));
        jLabel11.setPreferredSize(new java.awt.Dimension(430, 148));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7))
                                        .addGap(32, 32, 32))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnombrecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipodocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo_Electronico, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(btnRegistrar)
                .addGap(96, 96, 96)
                .addComponent(btnEliminar)
                .addGap(67, 67, 67)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnombrecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbTipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(txtNumero_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCorreo_Electronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(84, 84, 84)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEliminar))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jLabel10.setText("Busqueda");

        TablaRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRegistroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaRegistro);

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombrecompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecompletoActionPerformed

    private void txtnacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnacionalidadActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
     insertarDatos();    
      limpiarCajas(); 
      mostarDatos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       eliminarRegistro();
        mostarDatos();
         limpiarCajas(); 
    }//GEN-LAST:event_btnEliminarActionPerformed
public  void filtrarDatos(String Valor ){
   
   String[] titulos= {"id","Nombre completo ","Nacionalidad","Tipo de documento","Numero de documento","Telefono","Localidad","Direccion","Correo electronico","Contraseña"};
   String[] registros=new String[10];
   
   DefaultTableModel model=new DefaultTableModel(null,titulos);
   
   String SQL="select*from registro where Nombre_completo like '%"+Valor+"%'";
   try{
       
       
       Statement st=con.createStatement();
       ResultSet rs=st.executeQuery(SQL);
       
       
       while(rs.next()){
       registros[0]=rs.getString("id");   
       registros[1]=rs.getString("Nombre_completo");
       registros[2]=rs.getString("Nacionalidad");
       registros[3]=rs.getString("Tipo_documento");
       registros[4]=rs.getString("Numero_documento");
       registros[5]=rs.getString("Telefono");
       registros[6]=rs.getString("Localidad");
       registros[7]=rs.getString("Direccion");
       registros[8]=rs.getString("Correo_electronico");
       registros[9]=rs.getString("Contraseña");
       
       model.addRow(registros);
       }
               
     TablaRegistro.setModel(model);
     
   } catch (Exception e){
   
   JOptionPane.showMessageDialog(null,"Error al mostrar datos"+ e.getMessage());
   }
   
   
   }
    private void txtNumero_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero_DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero_DocumentoActionPerformed

    private void cbLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLocalidadActionPerformed

    private void TablaRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRegistroMouseClicked
     
        int filaSelecionada=TablaRegistro.rowAtPoint(evt.getPoint());
        
        txtnombrecompleto.setText(TablaRegistro.getValueAt(filaSelecionada,1).toString());
        txtnacionalidad.setText(TablaRegistro.getValueAt(filaSelecionada,2).toString());
        cbTipodocumento.setSelectedItem(TablaRegistro.getValueAt(filaSelecionada,3));
        txtNumero_Documento.setText(TablaRegistro.getValueAt(filaSelecionada,4).toString());
        txtTelefono.setText(TablaRegistro.getValueAt(filaSelecionada,5).toString());
        cbLocalidad.setSelectedItem(TablaRegistro.getValueAt(filaSelecionada,6));
        txtDireccion.setText(TablaRegistro.getValueAt(filaSelecionada,7).toString());
        txtCorreo_Electronico.setText(TablaRegistro.getValueAt(filaSelecionada,8).toString());
        txtContraseña.setText(TablaRegistro.getValueAt(filaSelecionada,9).toString());
     
        
           

    }//GEN-LAST:event_TablaRegistroMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
           ActualizarDatos(); 
          limpiarCajas(); 
      mostarDatos();
       
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
  filtrarDatos(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyReleased


          
          
          
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaRegistro;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbLocalidad;
    private javax.swing.JComboBox<String> cbTipodocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo_Electronico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNumero_Documento;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtnacionalidad;
    private javax.swing.JTextField txtnombrecompleto;
    // End of variables declaration//GEN-END:variables

    private static class connection {

        public connection() {
        }
    }
}
